// Generated by: gen
// TypeWriter: slice
// Directive: +gen on *Room

package game

import "errors"

// RoomSlice is a slice of type *Room. Use it where you would use []*Room.
type RoomSlice []*Room

// First returns the first element that returns true for the passed func. Returns error if no elements return true. See: http://clipperhouse.github.io/gen/#First
func (rcv RoomSlice) First(fn func(*Room) bool) (result *Room, err error) {
	for _, v := range rcv {
		if fn(v) {
			result = v
			return
		}
	}
	err = errors.New("no RoomSlice elements return true for passed func")
	return
}
