// Code generated by protoc-gen-go.
// source: proto_files/Messages.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	proto_files/Messages.proto

It has these top-level messages:
	GenMessage
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type GenMessage struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	PIdx             *int32  `protobuf:"varint,2,opt,name=pIdx,def=0" json:"pIdx,omitempty"`
	MsgId            *int32  `protobuf:"varint,3,req,name=msgId" json:"msgId,omitempty"`
	Buf              []byte  `protobuf:"bytes,4,opt,name=buf" json:"buf,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GenMessage) Reset()                    { *m = GenMessage{} }
func (m *GenMessage) String() string            { return proto.CompactTextString(m) }
func (*GenMessage) ProtoMessage()               {}
func (*GenMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_GenMessage_PIdx int32 = 0

func (m *GenMessage) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *GenMessage) GetPIdx() int32 {
	if m != nil && m.PIdx != nil {
		return *m.PIdx
	}
	return Default_GenMessage_PIdx
}

func (m *GenMessage) GetMsgId() int32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *GenMessage) GetBuf() []byte {
	if m != nil {
		return m.Buf
	}
	return nil
}

func init() {
	proto.RegisterType((*GenMessage)(nil), "messages.GenMessage")
}

var fileDescriptor0 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x8f, 0x4f, 0xcb, 0xcc, 0x49, 0x2d, 0xd6, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d,
	0xd6, 0x03, 0x0b, 0x0a, 0x71, 0xe4, 0x42, 0xf9, 0x4a, 0xee, 0x5c, 0x5c, 0xee, 0xa9, 0x79, 0x50,
	0x69, 0x21, 0x1e, 0x2e, 0x96, 0x92, 0xca, 0x82, 0x54, 0x09, 0x46, 0x05, 0x26, 0x0d, 0x4e, 0x21,
	0x7e, 0x2e, 0x96, 0x02, 0xcf, 0x94, 0x0a, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x56, 0x2b, 0x46, 0x03,
	0x21, 0x5e, 0x2e, 0xd6, 0xdc, 0xe2, 0x74, 0xcf, 0x14, 0x09, 0x66, 0xa0, 0x3c, 0xab, 0x10, 0x37,
	0x17, 0x73, 0x52, 0x69, 0x9a, 0x04, 0x0b, 0x50, 0x9a, 0x07, 0x10, 0x00, 0x00, 0xff, 0xff, 0x12,
	0x6c, 0x1c, 0x1d, 0x6f, 0x00, 0x00, 0x00,
}
