// Code generated by protoc-gen-go.
// source: proto_files/RoomMessage.proto
// DO NOT EDIT!

/*
Package room is a generated protocol buffer package.

It is generated from these files:
	proto_files/RoomMessage.proto

It has these top-level messages:
	Vec3
	Quat
	Color4
	Rpc
	CrtObj
	GetMisCmd
	Ready
	Empty
*/
package room

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Vec3 struct {
	X                *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Z                *float32 `protobuf:"fixed32,3,req,name=z" json:"z,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Vec3) Reset()                    { *m = Vec3{} }
func (m *Vec3) String() string            { return proto.CompactTextString(m) }
func (*Vec3) ProtoMessage()               {}
func (*Vec3) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Vec3) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Vec3) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Vec3) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

type Quat struct {
	X                *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Z                *float32 `protobuf:"fixed32,3,req,name=z" json:"z,omitempty"`
	W                *float32 `protobuf:"fixed32,4,req,name=w" json:"w,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Quat) Reset()                    { *m = Quat{} }
func (m *Quat) String() string            { return proto.CompactTextString(m) }
func (*Quat) ProtoMessage()               {}
func (*Quat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Quat) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Quat) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Quat) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func (m *Quat) GetW() float32 {
	if m != nil && m.W != nil {
		return *m.W
	}
	return 0
}

type Color4 struct {
	R                *float32 `protobuf:"fixed32,1,req,name=r" json:"r,omitempty"`
	G                *float32 `protobuf:"fixed32,2,req,name=g" json:"g,omitempty"`
	B                *float32 `protobuf:"fixed32,3,req,name=b" json:"b,omitempty"`
	A                *float32 `protobuf:"fixed32,4,req,name=a" json:"a,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Color4) Reset()                    { *m = Color4{} }
func (m *Color4) String() string            { return proto.CompactTextString(m) }
func (*Color4) ProtoMessage()               {}
func (*Color4) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Color4) GetR() float32 {
	if m != nil && m.R != nil {
		return *m.R
	}
	return 0
}

func (m *Color4) GetG() float32 {
	if m != nil && m.G != nil {
		return *m.G
	}
	return 0
}

func (m *Color4) GetB() float32 {
	if m != nil && m.B != nil {
		return *m.B
	}
	return 0
}

func (m *Color4) GetA() float32 {
	if m != nil && m.A != nil {
		return *m.A
	}
	return 0
}

type Rpc struct {
	NetId            *int32  `protobuf:"varint,1,req,name=netId" json:"netId,omitempty"`
	Method           *string `protobuf:"bytes,2,req,name=method" json:"method,omitempty"`
	Argbuf           []byte  `protobuf:"bytes,3,req,name=argbuf" json:"argbuf,omitempty"`
	Frame            *int32  `protobuf:"varint,4,req,name=frame" json:"frame,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Rpc) Reset()                    { *m = Rpc{} }
func (m *Rpc) String() string            { return proto.CompactTextString(m) }
func (*Rpc) ProtoMessage()               {}
func (*Rpc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Rpc) GetNetId() int32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

func (m *Rpc) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Rpc) GetArgbuf() []byte {
	if m != nil {
		return m.Argbuf
	}
	return nil
}

func (m *Rpc) GetFrame() int32 {
	if m != nil && m.Frame != nil {
		return *m.Frame
	}
	return 0
}

type CrtObj struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Pos              *Vec3   `protobuf:"bytes,2,req,name=pos" json:"pos,omitempty"`
	Rot              *Quat   `protobuf:"bytes,3,req,name=rot" json:"rot,omitempty"`
	Frame            *int32  `protobuf:"varint,4,req,name=frame" json:"frame,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CrtObj) Reset()                    { *m = CrtObj{} }
func (m *CrtObj) String() string            { return proto.CompactTextString(m) }
func (*CrtObj) ProtoMessage()               {}
func (*CrtObj) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CrtObj) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *CrtObj) GetPos() *Vec3 {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *CrtObj) GetRot() *Quat {
	if m != nil {
		return m.Rot
	}
	return nil
}

func (m *CrtObj) GetFrame() int32 {
	if m != nil && m.Frame != nil {
		return *m.Frame
	}
	return 0
}

type GetMisCmd struct {
	PlayerIndex      *int32 `protobuf:"varint,1,req,name=playerIndex" json:"playerIndex,omitempty"`
	Frame            *int32 `protobuf:"varint,2,req,name=frame" json:"frame,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetMisCmd) Reset()                    { *m = GetMisCmd{} }
func (m *GetMisCmd) String() string            { return proto.CompactTextString(m) }
func (*GetMisCmd) ProtoMessage()               {}
func (*GetMisCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetMisCmd) GetPlayerIndex() int32 {
	if m != nil && m.PlayerIndex != nil {
		return *m.PlayerIndex
	}
	return 0
}

func (m *GetMisCmd) GetFrame() int32 {
	if m != nil && m.Frame != nil {
		return *m.Frame
	}
	return 0
}

type Ready struct {
	Frame            *int32 `protobuf:"varint,1,req,name=frame" json:"frame,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Ready) Reset()                    { *m = Ready{} }
func (m *Ready) String() string            { return proto.CompactTextString(m) }
func (*Ready) ProtoMessage()               {}
func (*Ready) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Ready) GetFrame() int32 {
	if m != nil && m.Frame != nil {
		return *m.Frame
	}
	return 0
}

type Empty struct {
	Frame            *int32 `protobuf:"varint,1,req,name=frame" json:"frame,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Empty) GetFrame() int32 {
	if m != nil && m.Frame != nil {
		return *m.Frame
	}
	return 0
}

func init() {
	proto.RegisterType((*Vec3)(nil), "room.Vec3")
	proto.RegisterType((*Quat)(nil), "room.Quat")
	proto.RegisterType((*Color4)(nil), "room.Color4")
	proto.RegisterType((*Rpc)(nil), "room.Rpc")
	proto.RegisterType((*CrtObj)(nil), "room.CrtObj")
	proto.RegisterType((*GetMisCmd)(nil), "room.GetMisCmd")
	proto.RegisterType((*Ready)(nil), "room.Ready")
	proto.RegisterType((*Empty)(nil), "room.Empty")
}

var fileDescriptor0 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xd5, 0xfc, 0xa9, 0x94, 0x6b, 0x61, 0x30, 0x12, 0x64, 0x41, 0x42, 0x59, 0x60, 0x4a,
	0xa5, 0xd2, 0x6f, 0x10, 0x21, 0xd4, 0xa1, 0x42, 0x64, 0x80, 0x11, 0x39, 0xf5, 0x25, 0x2d, 0x8a,
	0x6b, 0xcb, 0x76, 0x45, 0xc3, 0xa7, 0x27, 0x3e, 0xb5, 0x8d, 0xd4, 0x85, 0xed, 0xf9, 0xdd, 0xfd,
	0x9e, 0xed, 0x07, 0xf7, 0xda, 0x28, 0xa7, 0xbe, 0xea, 0x6d, 0x8b, 0x76, 0x56, 0x2a, 0x25, 0x57,
	0x68, 0x2d, 0x6f, 0x30, 0x27, 0x9f, 0x45, 0xa6, 0xb7, 0xb2, 0x47, 0x88, 0x3e, 0x70, 0xfd, 0xcc,
	0x12, 0x18, 0x1d, 0xd2, 0xd1, 0x43, 0xf0, 0x14, 0x78, 0xd9, 0xa5, 0xc1, 0x49, 0xfe, 0xa6, 0xa1,
	0x97, 0xd9, 0x1c, 0xa2, 0xf7, 0x3d, 0x77, 0xff, 0x2e, 0x7a, 0xf9, 0x93, 0x46, 0xc4, 0x2c, 0x60,
	0x5c, 0xa8, 0x56, 0x99, 0x85, 0x37, 0xcd, 0x40, 0x35, 0x03, 0x55, 0x0d, 0x14, 0x3f, 0x52, 0x05,
	0x84, 0xa5, 0x5e, 0xb3, 0x2b, 0x88, 0x77, 0xe8, 0x96, 0x82, 0xb0, 0x98, 0x5d, 0xc3, 0x58, 0xa2,
	0xdb, 0x28, 0x41, 0x6c, 0xe2, 0xcf, 0xdc, 0x34, 0xd5, 0xbe, 0xa6, 0x80, 0xa9, 0x5f, 0xaf, 0x0d,
	0x97, 0x48, 0x21, 0x71, 0xf6, 0xd9, 0x5f, 0x6d, 0xdc, 0x5b, 0xf5, 0xcd, 0xa6, 0x10, 0x69, 0xee,
	0x36, 0x14, 0x93, 0xb0, 0x3b, 0x08, 0xb5, 0xb2, 0x94, 0x31, 0x99, 0x43, 0xee, 0x3b, 0xc8, 0xa9,
	0x80, 0x7e, 0xd0, 0xd7, 0x42, 0x61, 0xe7, 0x01, 0x7d, 0xf8, 0x22, 0x78, 0x06, 0xc9, 0x2b, 0xba,
	0xd5, 0xd6, 0x16, 0x52, 0xb0, 0x1b, 0x98, 0xe8, 0x96, 0x77, 0x68, 0x96, 0x3b, 0x81, 0x87, 0xe3,
	0x4b, 0xcf, 0x40, 0x40, 0xc0, 0x2d, 0xc4, 0x25, 0x72, 0xd1, 0x0d, 0xfe, 0xe8, 0xe4, 0xbf, 0x48,
	0xed, 0x2e, 0xfd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x6e, 0x8e, 0x86, 0xb7, 0x01, 0x00,
	0x00,
}
