// Code generated by protoc-gen-go.
// source: proto_files/WorldMessage.proto
// DO NOT EDIT!

/*
Package world_messages is a generated protocol buffer package.

It is generated from these files:
	proto_files/WorldMessage.proto

It has these top-level messages:
	PlayerEnterRoom
	EnterRoomReply
	Room
	ReplyMsg
	GetRoomListReply
	CreateRoomReply
	PlayerCreateRoom
	PlayerQuitRoom
	CreateRoom
	EnterRoom
	GetRoomList
	Login
	LoginReply
*/
package world_messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type EnterRoomResult int32

const (
	EnterRoomResult_Ok            EnterRoomResult = 1
	EnterRoomResult_AlreadyIn     EnterRoomResult = 2
	EnterRoomResult_OutOfCapacity EnterRoomResult = 3
	EnterRoomResult_RoomNotExists EnterRoomResult = 4
)

var EnterRoomResult_name = map[int32]string{
	1: "Ok",
	2: "AlreadyIn",
	3: "OutOfCapacity",
	4: "RoomNotExists",
}
var EnterRoomResult_value = map[string]int32{
	"Ok":            1,
	"AlreadyIn":     2,
	"OutOfCapacity": 3,
	"RoomNotExists": 4,
}

func (x EnterRoomResult) Enum() *EnterRoomResult {
	p := new(EnterRoomResult)
	*p = x
	return p
}
func (x EnterRoomResult) String() string {
	return proto.EnumName(EnterRoomResult_name, int32(x))
}
func (x *EnterRoomResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EnterRoomResult_value, data, "EnterRoomResult")
	if err != nil {
		return err
	}
	*x = EnterRoomResult(value)
	return nil
}
func (EnterRoomResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PlayerEnterRoom struct {
	RoomId           *int32 `protobuf:"varint,1,req,name=roomId" json:"roomId,omitempty"`
	PlayerIndex      *int32 `protobuf:"varint,2,req,name=playerIndex" json:"playerIndex,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerEnterRoom) Reset()                    { *m = PlayerEnterRoom{} }
func (m *PlayerEnterRoom) String() string            { return proto.CompactTextString(m) }
func (*PlayerEnterRoom) ProtoMessage()               {}
func (*PlayerEnterRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PlayerEnterRoom) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *PlayerEnterRoom) GetPlayerIndex() int32 {
	if m != nil && m.PlayerIndex != nil {
		return *m.PlayerIndex
	}
	return 0
}

type EnterRoomReply struct {
	Players          []int32          `protobuf:"varint,1,rep,name=players" json:"players,omitempty"`
	AllockedIndex    *int32           `protobuf:"varint,2,req,name=allockedIndex" json:"allockedIndex,omitempty"`
	Result           *EnterRoomResult `protobuf:"varint,3,req,name=result,enum=world_messages.EnterRoomResult" json:"result,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *EnterRoomReply) Reset()                    { *m = EnterRoomReply{} }
func (m *EnterRoomReply) String() string            { return proto.CompactTextString(m) }
func (*EnterRoomReply) ProtoMessage()               {}
func (*EnterRoomReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EnterRoomReply) GetPlayers() []int32 {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *EnterRoomReply) GetAllockedIndex() int32 {
	if m != nil && m.AllockedIndex != nil {
		return *m.AllockedIndex
	}
	return 0
}

func (m *EnterRoomReply) GetResult() EnterRoomResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return EnterRoomResult_Ok
}

type Room struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	PlayerCount      *int32 `protobuf:"varint,2,req,name=playerCount" json:"playerCount,omitempty"`
	Capacity         *int32 `protobuf:"varint,3,req,name=capacity" json:"capacity,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Room) Reset()                    { *m = Room{} }
func (m *Room) String() string            { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()               {}
func (*Room) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Room) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Room) GetPlayerCount() int32 {
	if m != nil && m.PlayerCount != nil {
		return *m.PlayerCount
	}
	return 0
}

func (m *Room) GetCapacity() int32 {
	if m != nil && m.Capacity != nil {
		return *m.Capacity
	}
	return 0
}

type ReplyMsg struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	MsgId            *int32  `protobuf:"varint,2,req,name=msgId" json:"msgId,omitempty"`
	Buff             []byte  `protobuf:"bytes,3,req,name=buff" json:"buff,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReplyMsg) Reset()                    { *m = ReplyMsg{} }
func (m *ReplyMsg) String() string            { return proto.CompactTextString(m) }
func (*ReplyMsg) ProtoMessage()               {}
func (*ReplyMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReplyMsg) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ReplyMsg) GetMsgId() int32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *ReplyMsg) GetBuff() []byte {
	if m != nil {
		return m.Buff
	}
	return nil
}

type GetRoomListReply struct {
	Rooms            []*Room `protobuf:"bytes,1,rep,name=rooms" json:"rooms,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRoomListReply) Reset()                    { *m = GetRoomListReply{} }
func (m *GetRoomListReply) String() string            { return proto.CompactTextString(m) }
func (*GetRoomListReply) ProtoMessage()               {}
func (*GetRoomListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetRoomListReply) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type CreateRoomReply struct {
	ErrorCode        *int32 `protobuf:"varint,1,opt,name=errorCode,def=0" json:"errorCode,omitempty"`
	Id               *int32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Capacity         *int32 `protobuf:"varint,3,req,name=capacity" json:"capacity,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateRoomReply) Reset()                    { *m = CreateRoomReply{} }
func (m *CreateRoomReply) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomReply) ProtoMessage()               {}
func (*CreateRoomReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

const Default_CreateRoomReply_ErrorCode int32 = 0

func (m *CreateRoomReply) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_CreateRoomReply_ErrorCode
}

func (m *CreateRoomReply) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CreateRoomReply) GetCapacity() int32 {
	if m != nil && m.Capacity != nil {
		return *m.Capacity
	}
	return 0
}

type PlayerCreateRoom struct {
	RoomId           *int32  `protobuf:"varint,1,req,name=roomId" json:"roomId,omitempty"`
	PlayerId         *string `protobuf:"bytes,2,req,name=playerId" json:"playerId,omitempty"`
	Capacity         *int32  `protobuf:"varint,3,req,name=capacity" json:"capacity,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerCreateRoom) Reset()                    { *m = PlayerCreateRoom{} }
func (m *PlayerCreateRoom) String() string            { return proto.CompactTextString(m) }
func (*PlayerCreateRoom) ProtoMessage()               {}
func (*PlayerCreateRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PlayerCreateRoom) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *PlayerCreateRoom) GetPlayerId() string {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return ""
}

func (m *PlayerCreateRoom) GetCapacity() int32 {
	if m != nil && m.Capacity != nil {
		return *m.Capacity
	}
	return 0
}

type PlayerQuitRoom struct {
	RoomId           *int32  `protobuf:"varint,1,req,name=roomId" json:"roomId,omitempty"`
	PlayerId         *string `protobuf:"bytes,2,req,name=playerId" json:"playerId,omitempty"`
	PlayerIndex      *int32  `protobuf:"varint,3,req,name=playerIndex" json:"playerIndex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerQuitRoom) Reset()                    { *m = PlayerQuitRoom{} }
func (m *PlayerQuitRoom) String() string            { return proto.CompactTextString(m) }
func (*PlayerQuitRoom) ProtoMessage()               {}
func (*PlayerQuitRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PlayerQuitRoom) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *PlayerQuitRoom) GetPlayerId() string {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return ""
}

func (m *PlayerQuitRoom) GetPlayerIndex() int32 {
	if m != nil && m.PlayerIndex != nil {
		return *m.PlayerIndex
	}
	return 0
}

type CreateRoom struct {
	Capacity         *int32 `protobuf:"varint,1,req,name=capacity" json:"capacity,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateRoom) Reset()                    { *m = CreateRoom{} }
func (m *CreateRoom) String() string            { return proto.CompactTextString(m) }
func (*CreateRoom) ProtoMessage()               {}
func (*CreateRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateRoom) GetCapacity() int32 {
	if m != nil && m.Capacity != nil {
		return *m.Capacity
	}
	return 0
}

type EnterRoom struct {
	RoomId           *int32 `protobuf:"varint,1,req,name=roomId" json:"roomId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EnterRoom) Reset()                    { *m = EnterRoom{} }
func (m *EnterRoom) String() string            { return proto.CompactTextString(m) }
func (*EnterRoom) ProtoMessage()               {}
func (*EnterRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *EnterRoom) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

type GetRoomList struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetRoomList) Reset()                    { *m = GetRoomList{} }
func (m *GetRoomList) String() string            { return proto.CompactTextString(m) }
func (*GetRoomList) ProtoMessage()               {}
func (*GetRoomList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type Login struct {
	PlayerId         *string `protobuf:"bytes,1,req,name=playerId" json:"playerId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Login) GetPlayerId() string {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return ""
}

type LoginReply struct {
	ErrorCode        *int32 `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *LoginReply) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func init() {
	proto.RegisterType((*PlayerEnterRoom)(nil), "world_messages.PlayerEnterRoom")
	proto.RegisterType((*EnterRoomReply)(nil), "world_messages.EnterRoomReply")
	proto.RegisterType((*Room)(nil), "world_messages.Room")
	proto.RegisterType((*ReplyMsg)(nil), "world_messages.ReplyMsg")
	proto.RegisterType((*GetRoomListReply)(nil), "world_messages.GetRoomListReply")
	proto.RegisterType((*CreateRoomReply)(nil), "world_messages.CreateRoomReply")
	proto.RegisterType((*PlayerCreateRoom)(nil), "world_messages.PlayerCreateRoom")
	proto.RegisterType((*PlayerQuitRoom)(nil), "world_messages.PlayerQuitRoom")
	proto.RegisterType((*CreateRoom)(nil), "world_messages.CreateRoom")
	proto.RegisterType((*EnterRoom)(nil), "world_messages.EnterRoom")
	proto.RegisterType((*GetRoomList)(nil), "world_messages.GetRoomList")
	proto.RegisterType((*Login)(nil), "world_messages.Login")
	proto.RegisterType((*LoginReply)(nil), "world_messages.LoginReply")
	proto.RegisterEnum("world_messages.EnterRoomResult", EnterRoomResult_name, EnterRoomResult_value)
}

var fileDescriptor0 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x49, 0xda, 0x9c, 0x97, 0xe9, 0xe5, 0x87, 0xeb, 0x09, 0x15, 0xe1, 0x4e, 0xd6, 0x97,
	0xc3, 0x87, 0x9e, 0x1c, 0xa8, 0xe8, 0x9b, 0x94, 0x7a, 0x14, 0xae, 0xad, 0xf6, 0xc5, 0xc7, 0x12,
	0x9b, 0x4d, 0x08, 0xdd, 0x66, 0xc3, 0xee, 0x06, 0x9b, 0xff, 0xde, 0xfd, 0x11, 0x6c, 0xda, 0x5a,
	0xf0, 0x29, 0x64, 0x66, 0xbe, 0x9f, 0xf9, 0xce, 0xcc, 0xc2, 0x4d, 0xc5, 0x99, 0x64, 0xab, 0xac,
	0xa0, 0x44, 0xdc, 0xff, 0x64, 0x9c, 0xa6, 0x33, 0x22, 0x44, 0x92, 0x93, 0x91, 0x49, 0xa0, 0xf0,
	0xb7, 0x8e, 0xad, 0xb6, 0x36, 0x28, 0xf0, 0x47, 0x88, 0xbe, 0xd3, 0xa4, 0x21, 0x7c, 0x52, 0x4a,
	0xc2, 0x97, 0x8c, 0x6d, 0x51, 0x08, 0x17, 0x5c, 0x7d, 0xa7, 0xe9, 0xd0, 0x79, 0xe3, 0xde, 0x79,
	0xe8, 0x05, 0x0c, 0x2a, 0x53, 0x32, 0x2d, 0x53, 0xb2, 0x1b, 0xba, 0x3a, 0x88, 0x0b, 0x08, 0xff,
	0x2a, 0x96, 0xa4, 0xa2, 0x0d, 0x8a, 0xe0, 0x99, 0x2d, 0x13, 0x4a, 0xd7, 0x53, 0xba, 0x97, 0x10,
	0x24, 0x94, 0xb2, 0xf5, 0x86, 0xa4, 0x1d, 0x25, 0xba, 0x57, 0x78, 0x22, 0x6a, 0x2a, 0x87, 0x3d,
	0xf5, 0x1f, 0x3e, 0xdc, 0x8e, 0x0e, 0x2d, 0x8d, 0x3a, 0x5c, 0x5d, 0x86, 0x3f, 0x43, 0xdf, 0xf8,
	0x02, 0x70, 0x8b, 0x13, 0x4f, 0x63, 0x56, 0x97, 0xb2, 0x25, 0xc7, 0x70, 0xb9, 0x4e, 0xaa, 0x64,
	0x5d, 0xc8, 0xc6, 0xb0, 0x3d, 0xfc, 0x01, 0x2e, 0x8d, 0xb9, 0x99, 0xc8, 0xd1, 0x15, 0xf4, 0x65,
	0x53, 0x11, 0x03, 0xf0, 0x51, 0x00, 0xde, 0x56, 0xe4, 0x6a, 0x46, 0x2b, 0x55, 0xc9, 0x5f, 0x75,
	0x96, 0x19, 0xd9, 0x15, 0xfe, 0x04, 0xf1, 0x23, 0x91, 0xba, 0xe9, 0x53, 0x21, 0xa4, 0x1d, 0xef,
	0x2d, 0x78, 0x7a, 0x2b, 0x76, 0xb8, 0xc1, 0xc3, 0xf5, 0xb1, 0x6b, 0x5d, 0x8d, 0x27, 0x10, 0x8d,
	0x39, 0x49, 0x24, 0xd9, 0xaf, 0xe5, 0x1a, 0x7c, 0xc2, 0x39, 0x53, 0x46, 0x53, 0xdd, 0xdb, 0xb9,
	0xf3, 0xbe, 0x38, 0xef, 0xdb, 0x59, 0xce, 0xd9, 0xfe, 0x06, 0xb1, 0x3d, 0xca, 0x1e, 0x76, 0x72,
	0x15, 0xa5, 0x6a, 0xaf, 0x62, 0x39, 0xfe, 0x3f, 0x38, 0x8f, 0x10, 0x5a, 0xce, 0x8f, 0xba, 0x90,
	0xff, 0x49, 0x39, 0xba, 0xb6, 0x05, 0xdd, 0x00, 0x74, 0xac, 0x74, 0x1b, 0x19, 0x0c, 0x7e, 0x0d,
	0xfe, 0xd9, 0xf7, 0x83, 0x03, 0x18, 0x74, 0xb6, 0x89, 0x5f, 0x81, 0xf7, 0xc4, 0xf2, 0xa2, 0x3c,
	0xe8, 0x6d, 0x8e, 0x82, 0x6f, 0x01, 0x4c, 0xca, 0x6e, 0xee, 0xf9, 0xe1, 0xe6, 0x14, 0xea, 0xdd,
	0x1c, 0xa2, 0xa3, 0xd7, 0x81, 0x2e, 0xc0, 0x5d, 0x6c, 0x62, 0x47, 0x1d, 0xd4, 0xff, 0x4a, 0x95,
	0xc7, 0xb4, 0x99, 0x96, 0xb1, 0xab, 0xc4, 0xc1, 0xa2, 0x96, 0x8b, 0x6c, 0xdc, 0x1a, 0x8d, 0x7b,
	0x3a, 0xa4, 0x75, 0x73, 0x26, 0x27, 0x3b, 0x65, 0x44, 0xc4, 0xfd, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x0d, 0x93, 0xe1, 0xfd, 0x2e, 0x03, 0x00, 0x00,
}
